<?php

use Illuminate\Database\Seeder;
use App\Food;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Food::insert([
            //1
            [
                'name' => 'ข้าวกระเพราไก่',
                'description' => 'ไก่',
                'image_url' => '/images/food/t.png',
                'is_recommend' => 1,
                'price' => 40.00,
                'discount' => 5,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกระเพราหมู',
                'description' => 'ไก่',
                'image_url' => '/images/food/kapraomoo.png',
                'is_recommend' => 1,
                'price' => 40.00,
                'discount' => 5,
                'category_id' => 2,
            ],
            [
                'name' => 'ข้าวกระเพราหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/food/kapraomookrop.png',
                'is_recommend' => 1,
                'price' => 45.00,
                'discount' => 5,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกระเพราเนื่อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/food/kapronue.png',
                'is_recommend' => 1,
                'price' => 45.00,
                'discount' => 5,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกระเพรากุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/food/kaprokung.png',
                'is_recommend' => 1,
                'price' => 50.00,
                'discount' => 5,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวไก่กระเทียม',
                'description' => 'ไก่',
                'image_url' => '/images/food/kaikrateam.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวหมูกระเทียม',
                'description' => 'หมู',
                'image_url' => '/images/food/mookrateam.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวหมูกรอบกระเทียม',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/food/mookropkrateam.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวเนื้อกระเทียม',
                'description' => 'เนื้อ',
                'image_url' => '/images/food/nuekrateam.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกุ้งกระเทียม',
                'description' => 'กุ้ง',
                'image_url' => '/images/food/krungkrateam.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกเผาไก่',
                'description' => 'ไก่',
                'image_url' => '/images/food/prikpaokai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกเผาหมู',
                'description' => 'หมู',
                'image_url' => '/images/food/prikpaomoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกเผาหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/food/prikpaomookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกเผาเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/food/prikpaonue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกเผากุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/food/prikpaokung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกแกงไก่',
                'description' => 'ไก่',
                'image_url' => '/images/food/prikkangkai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกแกงหมู',
                'description' => 'หมู',
                'image_url' => '/images/food/prikkangmoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกแกงหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/food/prikkangmookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกแกงเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/food/prikkangnue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกแกงกุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/food/prikkangkung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกสดไก่',
                'description' => 'ไก่',
                'image_url' => '/images/food/priksodkai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกสดหมู',
                'description' => 'หมู',
                'image_url' => '/images/food/priksodmoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกสดหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/food/priksodmookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกสดเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/food/priksodnue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพริกสดกุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/food/priksodkung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดไก่',
                'description' => 'ไก่',
                'image_url' => '/images/food/kaopadkai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดหมู',
                'description' => 'หมู',
                'image_url' => '/images/food/kaopadmoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/food/kaopadmookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/food/kaopadnue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดกุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/food/kaopadkung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวเขียวหวานไก่',
                'description' => 'ไก่',
                'image_url' => '/images/food/keowwankai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวเขียวหวานหมู',
                'description' => 'หมู',
                'image_url' => '/images/food/keowwanmoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวเขียวหวานหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/food/keowwanmookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวเขียวหวานเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/food/keowwannue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวเขียวหวานกุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/food/keowwankung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพะแนงไก่',
                'description' => 'ไก่',
                'image_url' => '/images/food/panangkai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพะแนงหมู',
                'description' => 'หมู',
                'image_url' => '/images/food/panangmoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพะแนงหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/food/panangmookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพะแนงเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/food/panangnue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวพะแนงกุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/food/panangkung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดขี้เมาไก่',
                'description' => 'ไก่',
                'image_url' => '/images/food/keemaokai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดขี้เมาหมู',
                'description' => 'หมู',
                'image_url' => '/images/food/keemaomoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดขี้เมาหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/food/keemaomookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดขี้เมาเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/foodkeemaonue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวผัดขี้เมากุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/food/keemaokung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ผัดมาม่าไก่',
                'description' => 'ไก่',
                'image_url' => '/images/food/padmamakai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ผัดมาม่าหมู',
                'description' => 'หมู',
                'image_url' => '/images/food/padmamamoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ผัดมาม่าหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/food/padmamamookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ผัดมาม่าเนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/food/padmamanue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ผัดมาม่ากุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/food/padmamakung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกะหรี่ไก่',
                'description' => 'ไก่',
                'image_url' => '/images/food/krareekai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกะหรี่หมู',
                'description' => 'หมู',
                'image_url' => '/images/food/krareemoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกะหรี่หมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/food/krareemookrop.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกะหรี่เนื้อ',
                'description' => 'เนื้อ',
                'image_url' => '/images/food/krareenue.png',
                'is_recommend' => 0,
                'price' => 45.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ข้าวกะหรี่กุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/food/krareekung.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 1,
            ],
            [
                'name' => 'ยำไข่ดาว',
                'description' => 'ไข่ดาว',
                'image_url' => '/images/food/yumkaidown.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 2,
            ],

            [
                'name' => 'ยำกุนเชียง',
                'description' => 'กุนเชียง',
                'image_url' => '/images/food/yumkuncheing.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 2,
            ],
            [
                'name' => 'ยำหมูมะนาว',
                'description' => 'หมู',
                'image_url' => '/images/food/yummoomanow.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 2,
            ],
            [
                'name' => 'ยำหมูกรอบ',
                'description' => 'หมูกรอบ',
                'image_url' => '/images/food/yummookrop.png',
                'is_recommend' => 0,
                'price' => 50.00,
                'discount' => 0,
                'category_id' => 2,
            ],
            [
                'name' => 'ต้มยำไก่',
                'description' => 'ไก่',
                'image_url' => '/images/food/tomyumkai.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 3,
            ],
            [
                'name' => 'ต้มยำกุ้ง',
                'description' => 'กุ้ง',
                'image_url' => '/images/food/tomyumkung.png',
                'is_recommend' => 0,
                'price' => 60.00,
                'discount' => 0,
                'category_id' => 3,
            ],
            [
                'name' => 'ต้มยำหมู',
                'description' => 'หมู',
                'image_url' => '/images/food/tomyummoo.png',
                'is_recommend' => 0,
                'price' => 40.00,
                'discount' => 0,
                'category_id' => 3,
            ],
            [
                'name' => 'พิซซ่าค็อตโต้',
                'description' => 'พิซซ่าแฮม_มะกอกดำ_ไข่ต้ม_มะเขือเทศ_ชีส',
                'image_url' => '/images/food/pizza_al_quattro.png',
                'is_recommend' => 0,
                'price' => 169.00,
                'discount' => 0,
                'category_id' => 5,
            ],
            [
                'name' => 'พิซซ่าคาลาซิงก้า',
                'description' => 'พิซซ่าซาลามี_หอมใหญ่_พริกใหญ่_มะเขือเทศ_ชีส',
                'image_url' => '/images/food/pizza_casalinga.png',
                'is_recommend' => 0,
                'price' => 169.00,
                'discount' => 0,
                'category_id' => 5,
            ],
            [
                'name' => 'เสต็กเนื้อรสพริกไทย',
                'description' => 'เสต็ก_เนื้อ_พริกไทยดำ',
                'image_url' => '/images/food/pepper_streak_breef.png',
                'is_recommend' => 0,
                'price' => 169.00,
                'discount' => 0,
                'category_id' => 6,
            ],
            [
                'name' => 'เสต็กสันในหมูพันเบคอน',
                'description' => 'เสต็ก_หมู_พันเบคอน',
                'image_url' => '/images/food/fillet_mignon.png',
                'is_recommend' => 0,
                'price' => 149.00,
                'discount' => 0,
                'category_id' => 6,
            ],
            [
                'name' => 'สปาเก็ตตี้',
                'description' => 'สปาเก็ตตี้ซอสเนื้อ',
                'image_url' => '/images/food/spaghetti_meatsauce.png',
                'is_recommend' => 0,
                'price' => 69.00,
                'discount' => 0,
                'category_id' => 7,
            ],
            [
                'name' => 'เพนเน่',
                'description' => 'เพนเน่ซอสเนื้อ',
                'image_url' => '/images/food/penne_meatsauce.png',
                'is_recommend' => 0,
                'price' => 69.00,
                'discount' => 0,
                'category_id' => 7,
            ]
        ]);
    }
}